networks:
  net-c1-as1:
    name: net-c1-as1
    ipam:
      config:
        - subnet: 10.201.1.0/24
          gateway: 10.201.1.254
  net-as2-as3:
    name: net-as2-as3
    ipam:
      config:
        - subnet: 10.2.3.0/24
          gateway: 10.2.3.254
  net-as1-as2:
    name: net-as1-as2
    ipam:
      config:
        - subnet: 10.1.2.0/24
          gateway: 10.1.2.254
  net-as1-as3:
    name: net-as1-as3
    ipam:
      config:
        - subnet: 10.1.3.0/24
          gateway: 10.1.3.254
  net-as3-as4:
    name: net-as3-as4
    ipam:
      config:
        - subnet: 10.3.4.0/24
          gateway: 10.3.4.254
  net-as2-as4:
    name: net-as2-as4
    ipam:
      config:
        - subnet: 10.2.4.0/24
          gateway: 10.2.4.254
  net-c2-as4:
    name: net-c2-as4
    ipam:
      config:
        - subnet: 10.202.4.0/24
          gateway: 10.202.4.254

services:
  router-1:
    image: openbgpd/openbgpd:8.3
    container_name: router-1
    networks:
      net-c1-as1:
        ipv4_address: 10.201.1.1
      net-as1-as2:
        ipv4_address: 10.1.2.1
      net-as1-as3:
        ipv4_address: 10.1.3.1
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd1.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                /entrypoint.sh bgpd -d -v
             "
  router-2:
    build: 
        context: .
        dockerfile: Dockerfile
    image: openbgpd-iptables
    container_name: router-2
    networks:
      net-as1-as2:
        ipv4_address: 10.1.2.2
      net-as2-as3:
        ipv4_address: 10.2.3.2
      #net-as2-as4:
      #  ipv4_address: 10.2.4.2
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd2.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                ip route add 10.202.4.0/24 via 10.2.3.3 &&
                nginx -g 'daemon on;' &&
                /entrypoint.sh bgpd -d -v
             "
  router-3:
    image: openbgpd/openbgpd:8.3
    container_name: router-3
    networks:
      net-as1-as3:
        ipv4_address: 10.1.3.3
      net-as2-as3:
        ipv4_address: 10.2.3.3
      net-as3-as4:
        ipv4_address: 10.3.4.3
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd3.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                /entrypoint.sh bgpd -d -v
             "

  router-4:
    image: openbgpd/openbgpd:8.3
    container_name: router-4
    networks:
      #net-as2-as4:
      #  ipv4_address: 10.2.4.4
      net-as3-as4:
        ipv4_address: 10.3.4.4
      net-c2-as4:
        ipv4_address: 10.202.4.1
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd4.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                /entrypoint.sh bgpd -d -v
             "

  host-1:
    image: lscr.io/linuxserver/firefox:latest
    #image: alpine
    container_name: host-1
    networks:
      net-c1-as1:
        ipv4_address: 10.201.1.201
    ports: 
        - 3000:3000
    cap_add:
        - NET_ADMIN
    command: sh -c "
                ip route del default &&
                ip route add default via 10.201.1.1 &&
                while true; do sleep 3600; done"

  host-2:
    image: nginx:alpine
    container_name: host-2
    networks:
      net-c2-as4:
        ipv4_address: 10.202.4.202
    cap_add:
        - NET_ADMIN
    command: sh -c "
              ip route del default &&
              ip route add default via 10.202.4.1 &&
              nginx -g 'daemon off;' " 
               
