networks:
  net-c1-as1:
     name: net-c1-as1
     ipam:
      config:
        - subnet: 10.201.1.0/24
          gateway: 10.201.1.254
  net-as1-as2:
     name: net-as1-as2
     ipam:
      config:
        - subnet: 10.1.2.0/24
          gateway: 10.1.2.254
  net-c2-as2:
     name: net-c2-as2
     ipam:
      config:
        - subnet: 10.202.2.0/24
          gateway: 10.202.2.254

services:
  router-1:
    image: openbgpd/openbgpd:latest
    container_name: router-1
    networks:
      net-c1-as1:
        ipv4_address: 10.201.1.1
      net-as1-as2:
        ipv4_address: 10.1.2.1
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd1.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                /entrypoint.sh bgpd -d -v
             "

  router-2:
    image: openbgpd/openbgpd:latest
    container_name: router-2
    networks:
     net-as1-as2:
        ipv4_address: 10.1.2.2
     net-c2-as2:
        ipv4_address: 10.202.2.2
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd2.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                /entrypoint.sh bgpd -d -v
             "

  host-1:
    image: alpine
    container_name: host-1
    networks:
      net-c1-as1:
        ipv4_address: 10.201.1.201
    cap_add:
        - NET_ADMIN
    command: sh -c "
                ip route del default &&
                ip route add default via 10.201.1.1 &&
                while true; do sleep 3600; done"
  host-2:
    image: alpine
    container_name: host-2
    networks:
      net-c2-as2:
        ipv4_address: 10.202.2.202
    cap_add:
        - NET_ADMIN
    command: sh -c "
                ip route del default &&
                ip route add default via 10.202.2.2 &&
                while true; do sleep 3600; done"

