networks:
   net-as65001:
     name: net-as65001
     ipam:
      config:
        - subnet: 13.37.0.0/24
          gateway: 13.37.0.254
   net-as65002:
     name: net-as65002
     ipam:
      config:
        - subnet: 40.4.0.0/24
          gateway: 40.4.0.254

services:
  router-1:
    image: openbgpd/openbgpd:latest
    container_name: router-1
    networks:
      net-as65001:
        ipv4_address: 13.37.0.1
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd1.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                ip route add default via 13.37.0.1 &&
                /entrypoint.sh bgpd -d -v
             "

  router-2:
    image: openbgpd/openbgpd:latest
    container_name: router-2
    networks:
     net-as65002:
        ipv4_address: 40.4.0.1
    cap_add:
        - ALL
    sysctls:
        - net.ipv4.ip_forward=1
    volumes:
      - ./config/bgpd2.conf:/etc/bgpd/bgpd.conf
    command: sh -c "
                ip route del default &&
                ip route add default via 40.4.0.1 &&
                /entrypoint.sh bgpd -d -v
             "

  host-1:
    image: alpine
    container_name: host-1
    networks:
      net-as65001:
        ipv4_address: 13.37.0.10
    cap_add:
        - NET_ADMIN 
    command: sh -c "
                ip route del default &&
                ip route add default via 13.37.0.1 &&
                while true; do sleep 3600; done"
  host-2:
    image: alpine
    container_name: host-2
    networks:
      net-as65002:
        ipv4_address: 40.4.0.10
    cap_add:
        - NET_ADMIN 
    command: sh -c "
                ip route del default &&
                ip route add default via 40.4.0.1 &&
                while true; do sleep 3600; done"

